version: '3'
services:
  my-spring:
    build: .
    ports:
     - 5000:5000
    container_name: spring-server
    volumes:
     - ./public:/public
    environment:
     - DB_HOST=${DB_HOST}
     - DB_USER=${DB_USER}
     - DB_PASS=${DB_PASS}

networks:
  default:
    external:
      name: intregrated-int221
